### ISSUE TITLE
原始数据缺少LinkedIn节点属性文件

### ISSUE THREAD

**Issue by ChenBaiyang** [BoChen-Daniel/MEgo2Vec-Embedding-Matched-Ego-Networks-for-User-Alignment-Across-Social-Networks#5]
您好！

阅读了您的论文后，我尝试在原始数据集上做实验，但您在百度网盘上发布的原始数据集中，似乎没有 包含LinkedIn的节点属性文件，请问方便提供一下吗？farstars@qq.com

感谢您的帮助！

**Comment by allanchen95** [comment]
你好，感谢关注我们的工作，我已将linkedin_data.p上传到原网盘中：https://pan.baidu.com/s/1b6_8jd8J9CGiCpyFBfZgoQ，可直接下载使用。

**Comment by ChenBaiyang** [comment]
Thank you for your prompt assistance.

**Comment by ChenBaiyang** [comment]
您好！

我从您提供的原始数据中重新构建了Arminer-Linkedin网络结构，但是由于 new_pairs.p 中提供的对齐用户的节点ID 和 原始网络中的节点ID 的编码不同，无法找到原始网络中的对齐关系。

而我的工作需要在原始网络中进行实验，能否烦劳您提供一下完整的用户对齐关系数据(Positive anchors)？

感谢您的帮助！
Bryan Chen
